FROM python:3.11-alpine
WORKDIR /app

# Install backend dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend source code (including the app folder and secrets)
COPY . .

# Copy the environment file (ensure hashed passwords use $$ in place of $)
COPY secrets/settings.env /app/settings.env
ENV ENV_FILE=/app/settings.env

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
